from typing import Any

class float64: ...

class datetime64:
    def __int__(self) -> int: ...

class ndarray:
    def __add__(self, other: Union[ndarray, int, float]) -> ndarray: ...
    def __sub__(self, other: Union[ndarray, int, float]) -> ndarray: ...
    def __eq__(self, other: Union[ndarray, int, float]) -> ndarray: ...
    def __lt__(self, other: Union[ndarray, int, float]) -> ndarray: ...
    def __gt__(self, other: Union[ndarray, int, float]) -> ndarray: ...
    def __le__(self, other: Union[ndarray, int, float]) -> ndarray: ...
    def __ge__(self, other: Union[ndarray, int, float]) -> ndarray: ...

def issubdtype(any, any) -> bool: ...
def flatnonzero(values: ndarray) -> ndarray: ...
def diff(values: ndarray) -> ndarray: ...
def all(values: ndarray) -> bool: ...

class R_:
    def __getitem__(self, *args) -> Any: ...

r_ = R_()
