#!/bin/sh
WEB_FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.js" "*.jsx" "*.html" "*.md" | sed 's| |\\ |g')
PY_FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.py" | sed 's| |\\ |g')

if [ -n "$WEB_FILES" ]; then

    # Prettify all selected files
    echo "$WEB_FILES" | xargs /usr/local/bin/prettier --write

    # Add back the modified/prettified files to staging
    echo "$WEB_FILES" | xargs git add
fi

if [ -n "$PY_FILES" ]; then
    # Format all selected files
    echo "$PY_FILES" | xargs /usr/local/bin/black

    # Add back the modified/prettified files to staging
    echo "$PY_FILES" | xargs git add
fi
