from typing import Optional, Any

class DataType: ...

def timestamp(unit, tz: Optional[str] = None) -> DataType: ...
def uint64() -> DataType: ...
def int8() -> DataType: ...
def dictionary(key: DataType, value: DataType) -> DataType: ...
def string() -> DataType: ...

class Array: ...

class Table:
    def __len__(self) -> int: ...
    @staticmethod
    def from_arrays(
        arrays: list[Array],
        names: Optional[list[str]] = None,
        metadata: Optional[dict[str, str]] = None,
    ) -> Table: ...
    def to_pandas() -> Any: ...

def array(values: list[Any], type: Optional[DataType] = None) -> Array: ...
